/**
 * 收费标准种子数据
 * 基于上海病理收费标准（2026年6月5日起执行）
 * 数据来源：20260605病理类医疗服务项目价格调整映射初稿20260521-KW.xlsx
 */

import { getDatabase } from '../src/database/DatabaseManager.js'
import { v4 as uuidv4 } from 'uuid'

export function seedFeeStandards(): void {
  const db = getDatabase()

  // 检查是否已有数据
  const count = db.prepare('SELECT COUNT(*) as count FROM fee_standards').get() as any
  if (count && count.count > 0) {
    console.log('Fee standards already exists, skipping seed')
    return
  }

  console.log('正在从Excel数据导入收费标准...')

  // 完整的收费编码数据（来自Excel文件）
  const standards = [
    // ===== 病理诊断费 =====
    {
      id: uuidv4(),
      code: '012100000010000',
      name: '病理诊断费（10张以内）',
      category: 'diagnosis',
      unit: '次',
      base_price: 105,
      tier_rules: JSON.stringify([
        { maxQuantity: 10, unitPrice: 105 },
        { maxQuantity: 20, unitPrice: 147 },
        { unitPrice: 189 }
      ]),
      cap_amount: null,
      is_self_pay: 0,
      effective_date: '2026-06-05',
    },
    {
      id: uuidv4(),
      code: '012100000010000a',
      name: '病理诊断费（超出部分每增加10张加收）',
      category: 'diagnosis',
      unit: '次',
      base_price: 42,
      tier_rules: null,
      cap_amount: null,
      is_self_pay: 0,
      effective_date: '2026-06-05',
    },
    {
      id: uuidv4(),
      code: '012100000010000b',
      name: '病理诊断费（最高加收）',
      category: 'diagnosis',
      unit: '次',
      base_price: 84,
      tier_rules: null,
      cap_amount: null,
      is_self_pay: 0,
      effective_date: '2026-06-05',
    },
    {
      id: uuidv4(),
      code: '012100000010001',
      name: '病理诊断费-术中冷冻病理诊断（加收）',
      category: 'frozen_diagnosis',
      unit: '次',
      base_price: 105,
      tier_rules: null,
      cap_amount: null,
      is_self_pay: 0,
      effective_date: '2026-06-05',
    },
    {
      id: uuidv4(),
      code: '012100000010001a',
      name: '病理诊断费-术中冷冻病理诊断（加收）（超出部分每增加10张加收）',
      category: 'frozen_diagnosis',
      unit: '次',
      base_price: 42,
      tier_rules: null,
      cap_amount: null,
      is_self_pay: 0,
      effective_date: '2026-06-05',
    },
    {
      id: uuidv4(),
      code: '012100000010001b',
      name: '病理诊断费-术中冷冻病理诊断（加收）（最高加收）',
      category: 'frozen_diagnosis',
      unit: '次',
      base_price: 84,
      tier_rules: null,
      cap_amount: null,
      is_self_pay: 0,
      effective_date: '2026-06-05',
    },
    {
      id: uuidv4(),
      code: '012100000010100',
      name: '病理诊断费-人工智能辅助诊断（扩展）',
      category: 'diagnosis_ai',
      unit: '次',
      base_price: 105,
      tier_rules: null,
      cap_amount: null,
      is_self_pay: 0,
      effective_date: '2026-06-05',
    },
    {
      id: uuidv4(),
      code: '012100000020000',
      name: '病理诊断费（远程）',
      category: 'diagnosis_remote',
      unit: '次',
      base_price: 105,
      tier_rules: JSON.stringify([
        { maxQuantity: 10, unitPrice: 105 },
        { maxQuantity: 20, unitPrice: 147 },
        { unitPrice: 189 }
      ]),
      cap_amount: null,
      is_self_pay: 1,
      effective_date: '2026-06-05',
    },
    {
      id: uuidv4(),
      code: '012100000020000a',
      name: '病理诊断费（远程）（超出部分每增加10张加收）',
      category: 'diagnosis_remote',
      unit: '次',
      base_price: 42,
      tier_rules: null,
      cap_amount: null,
      is_self_pay: 1,
      effective_date: '2026-06-05',
    },
    {
      id: uuidv4(),
      code: '012100000020000b',
      name: '病理诊断费（远程）（最高加收）',
      category: 'diagnosis_remote',
      unit: '次',
      base_price: 84,
      tier_rules: null,
      cap_amount: null,
      is_self_pay: 1,
      effective_date: '2026-06-05',
    },
    {
      id: uuidv4(),
      code: '012100000020100',
      name: '病理诊断费（远程）-人工智能辅助诊断（扩展）',
      category: 'diagnosis_remote_ai',
      unit: '次',
      base_price: 105,
      tier_rules: null,
      cap_amount: null,
      is_self_pay: 1,
      effective_date: '2026-06-05',
    },

    // ===== 病理标本处理费 =====
    {
      id: uuidv4(),
      code: '012100000030000',
      name: '病理标本处理费（组织病理-常规）（3个及以内）',
      category: 'specimen常规',
      unit: '每蜡块',
      base_price: 36,
      tier_rules: JSON.stringify([
        { maxQuantity: 3, unitPrice: 36 },
        { unitPrice: 7.2 }
      ]),
      cap_amount: 108,
      is_self_pay: 0,
      effective_date: '2026-06-05',
    },
    {
      id: uuidv4(),
      code: '012100000030000a',
      name: '病理标本处理费（组织病理-常规）（每增加1个蜡块加收）',
      category: 'specimen常规',
      unit: '每蜡块',
      base_price: 7.2,
      tier_rules: null,
      cap_amount: null,
      is_self_pay: 0,
      effective_date: '2026-06-05',
    },
    {
      id: uuidv4(),
      code: '012100000030000b',
      name: '病理标本处理费（组织病理-常规）（最高加收）',
      category: 'specimen常规',
      unit: '每蜡块',
      base_price: 72,
      tier_rules: null,
      cap_amount: null,
      is_self_pay: 0,
      effective_date: '2026-06-05',
    },
    {
      id: uuidv4(),
      code: '012100000030001',
      name: '病理标本处理费（组织病理-常规）-限时处理（加收）（3个及以内）',
      category: 'specimen常规_fast',
      unit: '每蜡块',
      base_price: 54,
      tier_rules: JSON.stringify([
        { maxQuantity: 3, unitPrice: 54 },
        { unitPrice: 10.8 }
      ]),
      cap_amount: 162,
      is_self_pay: 0,
      effective_date: '2026-06-05',
    },
    {
      id: uuidv4(),
      code: '012100000030001a',
      name: '病理标本处理费（组织病理-常规）-限时处理（加收）（每增加1个蜡块加收）',
      category: 'specimen常规_fast',
      unit: '每蜡块',
      base_price: 10.8,
      tier_rules: null,
      cap_amount: null,
      is_self_pay: 0,
      effective_date: '2026-06-05',
    },
    {
      id: uuidv4(),
      code: '012100000030001b',
      name: '病理标本处理费（组织病理-常规）-限时处理（加收）（最高加收）',
      category: 'specimen常规_fast',
      unit: '每蜡块',
      base_price: 108,
      tier_rules: null,
      cap_amount: null,
      is_self_pay: 0,
      effective_date: '2026-06-05',
    },
    {
      id: uuidv4(),
      code: '012100000040000',
      name: '病理标本处理费（组织病理-复杂）（5个及以内）',
      category: 'specimen_complex',
      unit: '每蜡块',
      base_price: 72,
      tier_rules: JSON.stringify([
        { maxQuantity: 5, unitPrice: 72 },
        { unitPrice: 14.4 }
      ]),
      cap_amount: 504,
      is_self_pay: 0,
      effective_date: '2026-06-05',
    },
    {
      id: uuidv4(),
      code: '012100000040000a',
      name: '病理标本处理费（组织病理-复杂）（每增加一个蜡块加收）',
      category: 'specimen_complex',
      unit: '每蜡块',
      base_price: 14.4,
      tier_rules: null,
      cap_amount: null,
      is_self_pay: 0,
      effective_date: '2026-06-05',
    },
    {
      id: uuidv4(),
      code: '012100000040000b',
      name: '病理标本处理费（组织病理-复杂）（最高加收）',
      category: 'specimen_complex',
      unit: '每蜡块',
      base_price: 144,
      tier_rules: null,
      cap_amount: null,
      is_self_pay: 0,
      effective_date: '2026-06-05',
    },
    {
      id: uuidv4(),
      code: '012100000050000',
      name: '病理标本处理费（细胞病理）',
      category: 'cyto_specimen',
      unit: '每玻片',
      base_price: 75,
      tier_rules: null,
      cap_amount: null,
      is_self_pay: 0,
      effective_date: '2026-06-05',
    },
    {
      id: uuidv4(),
      code: '012100000060000',
      name: '病理标本处理费（分子病理）（非原位杂交核酸检测标本）',
      category: 'mp_specimen',
      unit: '次',
      base_price: 100,
      tier_rules: null,
      cap_amount: null,
      is_self_pay: 1,
      effective_date: '2026-06-05',
    },
    {
      id: uuidv4(),
      code: '012100000070000',
      name: '病理标本处理费（电子显微镜病理）',
      category: 'em_specimen',
      unit: '每切片',
      base_price: 341,
      tier_rules: null,
      cap_amount: null,
      is_self_pay: 0,
      effective_date: '2026-06-05',
    },
    {
      id: uuidv4(),
      code: '012100000080000',
      name: '病理标本处理费（冷冻标本）（5个及以内）',
      category: 'frozen_specimen',
      unit: '每组织块',
      base_price: 94,
      tier_rules: JSON.stringify([
        { maxQuantity: 5, unitPrice: 94 },
        { unitPrice: 18.8 }
      ]),
      cap_amount: 658,
      is_self_pay: 0,
      effective_date: '2026-06-05',
    },
    {
      id: uuidv4(),
      code: '012100000080000a',
      name: '病理标本处理费（冷冻标本）（每增加1个组织块加收）',
      category: 'frozen_specimen',
      unit: '每组织块',
      base_price: 18.8,
      tier_rules: null,
      cap_amount: null,
      is_self_pay: 0,
      effective_date: '2026-06-05',
    },
    {
      id: uuidv4(),
      code: '012100000080000b',
      name: '病理标本处理费（冷冻标本）（最高加收）',
      category: 'frozen_specimen',
      unit: '每组织块',
      base_price: 188,
      tier_rules: null,
      cap_amount: null,
      is_self_pay: 0,
      effective_date: '2026-06-05',
    },
    {
      id: uuidv4(),
      code: '012100000090000',
      name: '细胞病理蜡块制作费',
      category: 'cyto_block',
      unit: '每蜡块',
      base_price: 40,
      tier_rules: null,
      cap_amount: null,
      is_self_pay: 1,
      effective_date: '2026-06-05',
    },
    {
      id: uuidv4(),
      code: '012100000100000',
      name: '病理标本切片复制费（第1-3切片）',
      category: 'white_slice',
      unit: '每切片',
      base_price: 7,
      tier_rules: JSON.stringify([
        { maxQuantity: 3, unitPrice: 7 },
        { unitPrice: 12 }
      ]),
      cap_amount: 165,
      is_self_pay: 1,
      effective_date: '2026-06-05',
    },
    {
      id: uuidv4(),
      code: '012100000100000a',
      name: '病理标本切片复制费（第4切片起）',
      category: 'white_slice',
      unit: '每切片',
      base_price: 12,
      tier_rules: null,
      cap_amount: null,
      is_self_pay: 1,
      effective_date: '2026-06-05',
    },
    {
      id: uuidv4(),
      code: '012100000100000b',
      name: '病理标本切片复制费（同一患者每次最高）',
      category: 'white_slice',
      unit: '每切片',
      base_price: 165,
      tier_rules: null,
      cap_amount: 165,
      is_self_pay: 1,
      effective_date: '2026-06-05',
    },

    // ===== 病理染色检查费 =====
    {
      id: uuidv4(),
      code: '012100000110000',
      name: '病理样本化学染色检查费（特殊染色及酶组织化学染色诊断）（第1-3切片）',
      category: 'ss',
      unit: '每切片',
      base_price: 80,
      tier_rules: JSON.stringify([
        { maxQuantity: 3, unitPrice: 80 },
        { unitPrice: 85 }
      ]),
      cap_amount: null,
      is_self_pay: 0,
      effective_date: '2026-06-05',
    },
    {
      id: uuidv4(),
      code: '012100000110000a',
      name: '病理样本化学染色检查费（特殊染色及酶组织化学染色诊断）（第4切片起）',
      category: 'ss',
      unit: '每切片',
      base_price: 85,
      tier_rules: null,
      cap_amount: null,
      is_self_pay: 0,
      effective_date: '2026-06-05',
    },
    {
      id: uuidv4(),
      code: '012100000110000b',
      name: '病理样本化学染色检查费（其他化学染色检查）',
      category: 'ss_other',
      unit: '每切片',
      base_price: 40,
      tier_rules: null,
      cap_amount: null,
      is_self_pay: 0,
      effective_date: '2026-06-05',
    },
    {
      id: uuidv4(),
      code: '012100000120000',
      name: '病理样本免疫组织化学染色检查费（常规）（第1-3切片）',
      category: 'ihc',
      unit: '每切片',
      base_price: 205,
      tier_rules: JSON.stringify([
        { maxQuantity: 3, unitPrice: 205 },
        { maxQuantity: 12, unitPrice: 210 },
        { unitPrice: 105 }
      ]),
      cap_amount: null,
      is_self_pay: 0,
      effective_date: '2026-06-05',
    },
    {
      id: uuidv4(),
      code: '012100000120000a',
      name: '病理样本免疫组织化学染色检查费（常规）（第4-12切片）',
      category: 'ihc',
      unit: '每切片',
      base_price: 210,
      tier_rules: null,
      cap_amount: null,
      is_self_pay: 0,
      effective_date: '2026-06-05',
    },
    {
      id: uuidv4(),
      code: '012100000120000b',
      name: '病理样本免疫组织化学染色检查费（常规）（第13切片起）',
      category: 'ihc',
      unit: '每切片',
      base_price: 105,
      tier_rules: null,
      cap_amount: null,
      is_self_pay: 0,
      effective_date: '2026-06-05',
    },
    {
      id: uuidv4(),
      code: '012100000120000c',
      name: '病理样本免疫组织化学染色检查费（免疫荧光染色诊断）（第1-3切片）',
      category: 'ihc_fluorescence',
      unit: '每切片',
      base_price: 123,
      tier_rules: JSON.stringify([
        { maxQuantity: 3, unitPrice: 123 },
        { maxQuantity: 12, unitPrice: 126 },
        { unitPrice: 63 }
      ]),
      cap_amount: null,
      is_self_pay: 0,
      effective_date: '2026-06-05',
    },
    {
      id: uuidv4(),
      code: '012100000120000d',
      name: '病理样本免疫组织化学染色检查费（免疫荧光染色诊断）（第4-12切片）',
      category: 'ihc_fluorescence',
      unit: '每切片',
      base_price: 126,
      tier_rules: null,
      cap_amount: null,
      is_self_pay: 0,
      effective_date: '2026-06-05',
    },
    {
      id: uuidv4(),
      code: '012100000120000e',
      name: '病理样本免疫组织化学染色检查费（免疫荧光染色诊断）（第13切片起）',
      category: 'ihc_fluorescence',
      unit: '每切片',
      base_price: 63,
      tier_rules: null,
      cap_amount: null,
      is_self_pay: 0,
      effective_date: '2026-06-05',
    },
    {
      id: uuidv4(),
      code: '012100000120001',
      name: '病理样本免疫组织化学染色检查费（常规）-多重染色（加收）',
      category: 'ihc_multi',
      unit: '每切片',
      base_price: 410,
      tier_rules: JSON.stringify([
        { maxQuantity: 3, unitPrice: 410 },
        { maxQuantity: 12, unitPrice: 420 },
        { unitPrice: 210 }
      ]),
      cap_amount: null,
      is_self_pay: 0,
      effective_date: '2026-06-05',
    },
    {
      id: uuidv4(),
      code: '012100000120001a',
      name: '病理样本免疫组织化学染色检查费（常规）-多重染色（加收）（第4切片开始）',
      category: 'ihc_multi',
      unit: '每切片',
      base_price: 420,
      tier_rules: null,
      cap_amount: null,
      is_self_pay: 0,
      effective_date: '2026-06-05',
    },
    {
      id: uuidv4(),
      code: '012100000120001b',
      name: '病理样本免疫组织化学染色检查费（常规）-多重染色（加收）（第13切片起）',
      category: 'ihc_multi',
      unit: '每切片',
      base_price: 210,
      tier_rules: null,
      cap_amount: null,
      is_self_pay: 0,
      effective_date: '2026-06-05',
    },
    {
      id: uuidv4(),
      code: '012100000130000',
      name: '病理样本免疫组织化学染色检查费（增强）（第1-3切片）',
      category: 'ihc_enhanced',
      unit: '每切片',
      base_price: 650,
      tier_rules: JSON.stringify([
        { maxQuantity: 3, unitPrice: 650 },
        { unitPrice: 655 }
      ]),
      cap_amount: null,
      is_self_pay: 1,
      effective_date: '2026-06-05',
    },
    {
      id: uuidv4(),
      code: '012100000130000a',
      name: '病理样本免疫组织化学染色检查费（增强）（第4切片起）',
      category: 'ihc_enhanced',
      unit: '每切片',
      base_price: 655,
      tier_rules: null,
      cap_amount: null,
      is_self_pay: 1,
      effective_date: '2026-06-05',
    },

    // ===== 原位杂交检测费 =====
    {
      id: uuidv4(),
      code: '012100000140000',
      name: '原位核酸杂交检测费（化学探针）（第1-3切片）',
      category: 'ish_chemical',
      unit: '每切片·每探针',
      base_price: 223,
      tier_rules: JSON.stringify([
        { maxQuantity: 3, unitPrice: 223 },
        { unitPrice: 228 }
      ]),
      cap_amount: null,
      is_self_pay: 0,
      effective_date: '2026-06-05',
    },
    {
      id: uuidv4(),
      code: '012100000140000a',
      name: '原位核酸杂交检测费（化学探针）（第4切片起）',
      category: 'ish_chemical',
      unit: '每切片·每探针',
      base_price: 228,
      tier_rules: null,
      cap_amount: null,
      is_self_pay: 0,
      effective_date: '2026-06-05',
    },
    {
      id: uuidv4(),
      code: '012100000150000',
      name: '原位核酸杂交检测费（荧光探针）（前3切片·探针每个）',
      category: 'fish',
      unit: '每切片·每探针',
      base_price: 1200,
      tier_rules: JSON.stringify([
        { maxQuantity: 3, unitPrice: 1200 },
        { unitPrice: 1205 }
      ]),
      cap_amount: 3600,
      is_self_pay: 0,
      effective_date: '2026-06-05',
    },
    {
      id: uuidv4(),
      code: '012100000150000a',
      name: '原位核酸杂交检测费（荧光探针）（第4切片·探针起）',
      category: 'fish',
      unit: '每切片·每探针',
      base_price: 1205,
      tier_rules: null,
      cap_amount: null,
      is_self_pay: 0,
      effective_date: '2026-06-05',
    },
    {
      id: uuidv4(),
      code: '012100000150000b',
      name: '原位核酸杂交检测费（荧光探针）（每增加一种探针加收）',
      category: 'fish',
      unit: '每切片·每探针',
      base_price: 1205,
      tier_rules: null,
      cap_amount: null,
      is_self_pay: 0,
      effective_date: '2026-06-05',
    },
    {
      id: uuidv4(),
      code: '012100000150000c',
      name: '原位核酸杂交检测费（荧光探针）（最多加收）',
      category: 'fish',
      unit: '每切片·每探针',
      base_price: 2410,
      tier_rules: null,
      cap_amount: 3600,
      is_self_pay: 0,
      effective_date: '2026-06-05',
    },

    // ===== 分子病理检测费 =====
    {
      id: uuidv4(),
      code: '012100000160000',
      name: '聚合酶链反应法检测费（病理样本）',
      category: 'pcr',
      unit: '每位点',
      base_price: 223,
      tier_rules: JSON.stringify([
        { unitPrice: 223 }
      ]),
      cap_amount: 2000,
      is_self_pay: 0,
      effective_date: '2026-06-05',
    },
    {
      id: uuidv4(),
      code: '012100000160000a',
      name: '聚合酶链反应法检测费（病理样本）（每增加一个位点加收）',
      category: 'pcr',
      unit: '每位点',
      base_price: 100,
      tier_rules: null,
      cap_amount: null,
      is_self_pay: 0,
      effective_date: '2026-06-05',
    },
    {
      id: uuidv4(),
      code: '012100000160000b',
      name: '聚合酶链反应法检测费（病理样本）（每次最高）',
      category: 'pcr',
      unit: '次',
      base_price: 2000,
      tier_rules: null,
      cap_amount: 2000,
      is_self_pay: 0,
      effective_date: '2026-06-05',
    },
    {
      id: uuidv4(),
      code: '012100000170000',
      name: '实时荧光聚合酶链反应法检测费（病理样本）',
      category: 'pcr_fluorescence',
      unit: '每位点',
      base_price: 334,
      tier_rules: JSON.stringify([
        { unitPrice: 334 }
      ]),
      cap_amount: 4405,
      is_self_pay: 0,
      effective_date: '2026-06-05',
    },
    {
      id: uuidv4(),
      code: '012100000170000a',
      name: '实时荧光聚合酶链反应法检测费（病理样本）（每增加一个位点加收）',
      category: 'pcr_fluorescence',
      unit: '每位点',
      base_price: 200,
      tier_rules: null,
      cap_amount: null,
      is_self_pay: 0,
      effective_date: '2026-06-05',
    },
    {
      id: uuidv4(),
      code: '012100000170000b',
      name: '实时荧光聚合酶链反应法检测费（病理样本）（每次最高）',
      category: 'pcr_fluorescence',
      unit: '次',
      base_price: 4405,
      tier_rules: null,
      cap_amount: 4405,
      is_self_pay: 0,
      effective_date: '2026-06-05',
    },
    {
      id: uuidv4(),
      code: '012100000180000',
      name: '双脱氧链终止核酸测序法检测费（病理样本）',
      category: 'sanger',
      unit: '每靶序列',
      base_price: 450,
      tier_rules: JSON.stringify([
        { unitPrice: 450 }
      ]),
      cap_amount: 4405,
      is_self_pay: 0,
      effective_date: '2026-06-05',
    },
    {
      id: uuidv4(),
      code: '012100000180000a',
      name: '双脱氧链终止核酸测序法检测费（病理样本）（每增加一个靶序列加收）',
      category: 'sanger',
      unit: '每靶序列',
      base_price: 135,
      tier_rules: null,
      cap_amount: null,
      is_self_pay: 0,
      effective_date: '2026-06-05',
    },
    {
      id: uuidv4(),
      code: '012100000180000b',
      name: '双脱氧链终止核酸测序法检测费（病理样本）（每次最高）',
      category: 'sanger',
      unit: '次',
      base_price: 4405,
      tier_rules: null,
      cap_amount: 4405,
      is_self_pay: 0,
      effective_date: '2026-06-05',
    },
    {
      id: uuidv4(),
      code: '012100000190000',
      name: '焦磷酸核酸测序法检测费（病理样本）',
      category: 'pyrosequencing',
      unit: '每靶序列',
      base_price: 450,
      tier_rules: JSON.stringify([
        { unitPrice: 450 }
      ]),
      cap_amount: 4405,
      is_self_pay: 1,
      effective_date: '2026-06-05',
    },
    {
      id: uuidv4(),
      code: '012100000190000a',
      name: '焦磷酸核酸测序法检测费（病理样本）（每增加一个靶序列加收）',
      category: 'pyrosequencing',
      unit: '每靶序列',
      base_price: 135,
      tier_rules: null,
      cap_amount: null,
      is_self_pay: 1,
      effective_date: '2026-06-05',
    },
    {
      id: uuidv4(),
      code: '012100000190000b',
      name: '焦磷酸核酸测序法检测费（病理样本）（每次最高）',
      category: 'pyrosequencing',
      unit: '次',
      base_price: 4405,
      tier_rules: null,
      cap_amount: 4405,
      is_self_pay: 1,
      effective_date: '2026-06-05',
    },
    {
      id: uuidv4(),
      code: '012100000200000',
      name: '高通量测序法检测费（病理样本）',
      category: 'ngs',
      unit: '每面板',
      base_price: 1800,
      tier_rules: JSON.stringify([
        { unitPrice: 1800 }
      ]),
      cap_amount: 9800,
      is_self_pay: 1,
      effective_date: '2026-06-05',
    },
    {
      id: uuidv4(),
      code: '012100000200000a',
      name: '高通量测序法检测费（病理样本）（每增加一个面板加收）',
      category: 'ngs',
      unit: '每面板',
      base_price: 1350,
      tier_rules: null,
      cap_amount: null,
      is_self_pay: 1,
      effective_date: '2026-06-05',
    },
    {
      id: uuidv4(),
      code: '012100000200000b',
      name: '高通量测序法检测费（病理样本）（每次最高）',
      category: 'ngs',
      unit: '次',
      base_price: 9800,
      tier_rules: null,
      cap_amount: 9800,
      is_self_pay: 1,
      effective_date: '2026-06-05',
    },

    // ===== 活检取材费 =====
    {
      id: uuidv4(),
      code: '011201000010000',
      name: '活检取材费（钳夹）',
      category: 'biopsy_clamp',
      unit: '次',
      base_price: 113,
      tier_rules: null,
      cap_amount: null,
      is_self_pay: 0,
      effective_date: '2026-06-05',
    },
    {
      id: uuidv4(),
      code: '011201000020000',
      name: '活检取材费（Ⅰ类穿刺）',
      category: 'biopsy_1',
      unit: '次',
      base_price: 50,
      tier_rules: null,
      cap_amount: null,
      is_self_pay: 0,
      effective_date: '2026-06-05',
    },
    {
      id: uuidv4(),
      code: '011201000030000',
      name: '活检取材费（Ⅱ类穿刺）-胸腹',
      category: 'biopsy_2',
      unit: '次',
      base_price: 124,
      tier_rules: null,
      cap_amount: null,
      is_self_pay: 0,
      effective_date: '2026-06-05',
    },
    {
      id: uuidv4(),
      code: '011201000030000a',
      name: '活检取材费（Ⅱ类穿刺）-腰椎',
      category: 'biopsy_2',
      unit: '次',
      base_price: 124,
      tier_rules: null,
      cap_amount: null,
      is_self_pay: 0,
      effective_date: '2026-06-05',
    },
    {
      id: uuidv4(),
      code: '011201000030000b',
      name: '活检取材费（Ⅱ类穿刺）-膀胱',
      category: 'biopsy_2',
      unit: '次',
      base_price: 124,
      tier_rules: null,
      cap_amount: null,
      is_self_pay: 0,
      effective_date: '2026-06-05',
    },
    {
      id: uuidv4(),
      code: '011201000040000',
      name: '活检取材费（Ⅲ类穿刺）-甲状腺',
      category: 'biopsy_3',
      unit: '次',
      base_price: 360,
      tier_rules: null,
      cap_amount: null,
      is_self_pay: 0,
      effective_date: '2026-06-05',
    },
    {
      id: uuidv4(),
      code: '011201000040000a',
      name: '活检取材费（Ⅲ类穿刺）-前列腺',
      category: 'biopsy_3',
      unit: '次',
      base_price: 360,
      tier_rules: null,
      cap_amount: null,
      is_self_pay: 0,
      effective_date: '2026-06-05',
    },
    {
      id: uuidv4(),
      code: '011201000040000b',
      name: '活检取材费（Ⅲ类穿刺）-胰腺',
      category: 'biopsy_3',
      unit: '次',
      base_price: 360,
      tier_rules: null,
      cap_amount: null,
      is_self_pay: 0,
      effective_date: '2026-06-05',
    },
    {
      id: uuidv4(),
      code: '011201000040000c',
      name: '活检取材费（Ⅲ类穿刺）-肾',
      category: 'biopsy_3',
      unit: '次',
      base_price: 360,
      tier_rules: null,
      cap_amount: null,
      is_self_pay: 0,
      effective_date: '2026-06-05',
    },
    {
      id: uuidv4(),
      code: '011201000050000',
      name: '活检取材费（Ⅳ类穿刺）-颅内',
      category: 'biopsy_4',
      unit: '次',
      base_price: 140,
      tier_rules: null,
      cap_amount: null,
      is_self_pay: 0,
      effective_date: '2026-06-05',
    },
    {
      id: uuidv4(),
      code: '011201000050000a',
      name: '活检取材费（Ⅳ类穿刺）-眼内',
      category: 'biopsy_4',
      unit: '次',
      base_price: 140,
      tier_rules: null,
      cap_amount: null,
      is_self_pay: 0,
      effective_date: '2026-06-05',
    },
    {
      id: uuidv4(),
      code: '011201000050000b',
      name: '活检取材费（Ⅳ类穿刺）-脊髓',
      category: 'biopsy_4',
      unit: '次',
      base_price: 140,
      tier_rules: null,
      cap_amount: null,
      is_self_pay: 0,
      effective_date: '2026-06-05',
    },
    {
      id: uuidv4(),
      code: '011201000050000c',
      name: '活检取材费（Ⅳ类穿刺）-心肌',
      category: 'biopsy_4',
      unit: '次',
      base_price: 140,
      tier_rules: null,
      cap_amount: null,
      is_self_pay: 0,
      effective_date: '2026-06-05',
    },
    {
      id: uuidv4(),
      code: '011201000060000',
      name: '活检取材费（切开）（骨肿瘤切开活检术）',
      category: 'biopsy_open',
      unit: '次',
      base_price: 2380,
      tier_rules: null,
      cap_amount: null,
      is_self_pay: 0,
      effective_date: '2026-06-05',
    },
    {
      id: uuidv4(),
      code: '011201000060000a',
      name: '活检取材费（切开）（其他切开活检）',
      category: 'biopsy_open',
      unit: '次',
      base_price: 357,
      tier_rules: null,
      cap_amount: null,
      is_self_pay: 0,
      effective_date: '2026-06-05',
    },
    {
      id: uuidv4(),
      code: '011201000070000',
      name: '活检取材费（经皮介入）',
      category: 'biopsy_interventional',
      unit: '次',
      base_price: 250,
      tier_rules: null,
      cap_amount: null,
      is_self_pay: 0,
      effective_date: '2026-06-05',
    },
    {
      id: uuidv4(),
      code: '011201000080000',
      name: '活检取材费（内镜下）',
      category: 'biopsy_endoscopy',
      unit: '次',
      base_price: 200,
      tier_rules: null,
      cap_amount: null,
      is_self_pay: 0,
      effective_date: '2026-06-05',
    },
  ]

  const insertStmt = db.prepare(`
    INSERT INTO fee_standards (id, code, name, category, unit, base_price, tier_rules, cap_amount, is_self_pay, effective_date)
    VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
  `)

  for (const s of standards) {
    insertStmt.run(
      s.id, s.code, s.name, s.category, s.unit, s.base_price,
      s.tier_rules, s.cap_amount, s.is_self_pay, s.effective_date
    )
  }

  console.log(`收费标准导入完成: ${standards.length} 条`)
}

// 直接运行
seedFeeStandards()
